# Generated by Django 4.2.6 on 2023-11-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asri', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='asri',
        ),
    ]
